In [1]:
import pandas as pd
import numpy as np

import copy
#https://www.kaggle.com/mylesoneill/world-university-rankings
#https://www.kaggle.com/malapatiravi/graduate-school-admission-data/home

In [2]:
from sklearn.neighbors import NearestNeighbors

In [3]:
from rec_room.datasets import load_us_colleges_dataset

In [4]:
df = load_us_colleges_dataset()
df

gre   gpa  rank                                        name
0    700  3.65     2  University of Illinois at Urbana-Champaign
1    700  3.27     2           Washington University in St Louis
2    640  3.35     3                        Creighton University
3    600  3.47     2                     University of Wisconsin
4    700  4.00     1                          Harvard University
..   ...   ...   ...                                         ...
156  580  3.50     2                   Colorado State University
157  560  2.71     3                    Florida State University
158  620  3.21     4                       Texas Tech University
159  300  3.01     3        Oregon Health and Science University
160  680  3.85     3                             Rush University

[161 rows x 4 columns]

#### User Selection
1. User selects i colleges

    `df = df[df['name'].isin(colleges)]`
    
    `df[df['name'].isin(['Harvard University', 'Texas Tech University'])]`
    
    
2. User selects j features
    
    `df = df[feats]`
    
    `df = df[['gre','gpa']]`
    

3. User selects k recommendations to return (i.e., top k results)

    `df.iloc[rec[0][:k],]`
    
    `df.iloc[rec[0][:3],]`

In [5]:
x = df.head(10)
x

gre   gpa  rank                                        name
0  700  3.65     2  University of Illinois at Urbana-Champaign
1  700  3.27     2           Washington University in St Louis
2  640  3.35     3                        Creighton University
3  600  3.47     2                     University of Wisconsin
4  700  4.00     1                          Harvard University
5  580  3.34     2                             Rice University
6  780  3.87     4                      Saint Louis University
7  520  2.98     2            University of California, Irvine
8  500  3.31     3         State University of New York Albany
9  760  3.35     3                      University of Missouri

In [6]:
y = x.pop('name')
y

0    University of Illinois at Urbana-Champaign
1             Washington University in St Louis
2                          Creighton University
3                       University of Wisconsin
4                            Harvard University
5                               Rice University
6                        Saint Louis University
7              University of California, Irvine
8           State University of New York Albany
9                        University of Missouri
Name: name, dtype: object

In [7]:
inst = [650, 3.5, 1]
neigh = NearestNeighbors(len(x))
neigh.fit(x.values)
rec = neigh.kneighbors([inst], return_distance=False) # [inst]
rec

array([[2, 4, 3, 0, 1, 5, 9, 7, 6, 8]])

In [8]:
rec[0][:3]

array([2, 4, 3])

In [240]:
df.iloc[rec[0],]

gre   gpa  rank                                        name
2  640  3.35     3                        Creighton University
4  700  4.00     1                          Harvard University
3  600  3.47     2                     University of Wisconsin
0  700  3.65     2  University of Illinois at Urbana-Champaign
1  700  3.27     2           Washington University in St Louis
5  580  3.34     2                             Rice University
9  760  3.35     3                      University of Missouri
7  520  2.98     2            University of California, Irvine
6  780  3.87     4                      Saint Louis University
8  500  3.31     3         State University of New York Albany

In [9]:
x = df.copy()

In [11]:
x.shape

(161, 4)

In [12]:
z = x.pop('name')

In [14]:
n2 = NearestNeighbors(len(x))
n2.fit(x.values)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=161, p=2,
                 radius=1.0)

In [15]:
rec = n2.kneighbors([inst], return_distance=False) # [inst]
rec

array([[123,  33,  18,  81,  35, 101,  54, 148, 135, 125,  12,   2, 102,
        132,  60,  80, 104,  89,  83,  46, 142,  63,  30,  11, 145, 144,
         72, 140,  37,  98,  17,  96, 105,  97, 160,  22, 121, 158,  88,
         85,  43,  13,  69,  73,   4,  19,   3,  95, 113,   0, 127,   1,
         28,  93,  82, 155, 151, 156,  65,   5,  10, 118,  67,  53,  15,
        137,  51,  36,  32,  38,  91,  24, 112, 154,  25, 126, 128, 110,
         90,  86, 157,  50, 149,  71,  84,  77,  92, 103,  74,  31,  68,
         57,  14,  99,  27,   9,  21, 134,  52, 106, 152, 146,  59,  26,
          7,  70,  41, 107,  48,   6,  87,  66, 124,  20, 131,  47,  75,
         62,  29, 130,  61,   8,  78, 136,  23, 119, 147,  40, 129,  58,
        114,  34,  44,  42, 111,  45, 139, 116,  64,  16, 133, 141,  94,
         79, 100,  49, 138,  56, 109, 120, 150, 117,  76, 108, 115, 122,
        153,  39,  55, 143, 159]])

In [16]:
rec[0][:3]

array([123,  33,  18])

In [18]:
len(rec[0])

161

In [30]:
df.iloc[rec[0][:10],]

gre   gpa  rank                                               name
123  640  3.63     1                    Georgia Institute of Technology
33   660  3.32     1                               Princeton University
18   660  4.00     1              Massachusetts Institute of Technology
81   640  3.50     2                University of California, Riverside
35   660  3.49     2               University of California, Santa Cruz
101  660  3.44     2                             University of Delaware
54   660  3.33     2                             Stony Brook University
148  640  3.93     2  University of Medicine and Dentistry of New Je...
135  660  3.94     2                                Brandeis University
125  660  4.00     2                    University of Wisconsin-Madison

In [32]:
z.iloc[rec[0][:10],]

123                      Georgia Institute of Technology
33                                  Princeton University
18                 Massachusetts Institute of Technology
81                   University of California, Riverside
35                  University of California, Santa Cruz
101                               University of Delaware
54                                Stony Brook University
148    University of Medicine and Dentistry of New Je...
135                                  Brandeis University
125                      University of Wisconsin-Madison
Name: name, dtype: object

In [ ]:
inst = [650, 3.5, 1]

In [20]:
import joblib
from rec_room import ROOT_DIR
from os.path import join

In [24]:
fp = join(ROOT_DIR, 'recommenders')
fn = 'us_colleges_rs.sav'
f1 = join(fp, fn)

In [26]:
f1

'/home/jdpena/Documents/EdTech_CS6460/rec-room/rec_room/recommenders/us_colleges_rs.sav'

In [27]:
yn = 'us_colleges_labels.sav'
f2 = join(fp, yn)
f2

'/home/jdpena/Documents/EdTech_CS6460/rec-room/rec_room/recommenders/us_colleges_labels.sav'

In [33]:
joblib.dump(n2, f1)
joblib.dump(z, f2)

['/home/jdpena/Documents/EdTech_CS6460/rec-room/rec_room/recommenders/us_colleges_labels.sav']

In [34]:
n4 = joblib.load(f1)
y4 = joblib.load(f2)

In [36]:
y4

0      University of Illinois at Urbana-Champaign
1               Washington University in St Louis
2                            Creighton University
3                         University of Wisconsin
4                              Harvard University
                          ...                    
156                     Colorado State University
157                      Florida State University
158                         Texas Tech University
159          Oregon Health and Science University
160                               Rush University
Name: name, Length: 161, dtype: object

In [37]:
r2 = n4.kneighbors([inst], return_distance=False) # [inst]
r2

array([[123,  33,  18,  81,  35, 101,  54, 148, 135, 125,  12,   2, 102,
        132,  60,  80, 104,  89,  83,  46, 142,  63,  30,  11, 145, 144,
         72, 140,  37,  98,  17,  96, 105,  97, 160,  22, 121, 158,  88,
         85,  43,  13,  69,  73,   4,  19,   3,  95, 113,   0, 127,   1,
         28,  93,  82, 155, 151, 156,  65,   5,  10, 118,  67,  53,  15,
        137,  51,  36,  32,  38,  91,  24, 112, 154,  25, 126, 128, 110,
         90,  86, 157,  50, 149,  71,  84,  77,  92, 103,  74,  31,  68,
         57,  14,  99,  27,   9,  21, 134,  52, 106, 152, 146,  59,  26,
          7,  70,  41, 107,  48,   6,  87,  66, 124,  20, 131,  47,  75,
         62,  29, 130,  61,   8,  78, 136,  23, 119, 147,  40, 129,  58,
        114,  34,  44,  42, 111,  45, 139, 116,  64,  16, 133, 141,  94,
         79, 100,  49, 138,  56, 109, 120, 150, 117,  76, 108, 115, 122,
        153,  39,  55, 143, 159]])

In [38]:
y4.iloc[rec[0][:10],]

123                      Georgia Institute of Technology
33                                  Princeton University
18                 Massachusetts Institute of Technology
81                   University of California, Riverside
35                  University of California, Santa Cruz
101                               University of Delaware
54                                Stony Brook University
148    University of Medicine and Dentistry of New Je...
135                                  Brandeis University
125                      University of Wisconsin-Madison
Name: name, dtype: object